# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ef789e6fecd84d9564ee967281bc59b18e1fd0bfd62daabc76adabd9caa4acd96f8326b77c9360dbbdbc3ba9a170f41840c018c8cedf931807ca19d773b2ea93

test:
  secret_key_base: ca06022e07344fabea433a6d127354afbd2f04176e72c8e3582b8b646f9f267177d0bd8d1c0d4890956d5fec207a15dc44da7692eb4d24866af42d0639da4c0d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
